config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('museum.urls')),
]

museum/urls.py
from django.urls import path
from django.shortcuts import redirect
from . import views
app_name = 'museum'


urlpatterns = [
    path('store', views.StoreList.as_view(), name='store_list'),
    path('store/<int:pk>/staffs/', views.StaffList.as_view(), name='staff_list'),
    path('staff/<int:pk>/calendar/', views.StaffCalendar.as_view(), name='calendar'),
    path('staff/<int:pk>/calendar/<int:year>/<int:month>/<int:day>/', views.StaffCalendar.as_view(), name='calendar'),
    path('staff/<int:pk>/booking/<int:year>/<int:month>/<int:day>/<int:hour>/', views.Booking.as_view(), name='booking'),
    path('posts', views.post_list, name='post_list'),
    path('posts/<int:post_id>', views.post_show, name="post_show"),
    path('news', views.news, name="news"),
    path('news/<int:news_id>', views.news_show, name="news_show"),
    path('thanks', views.thanks, name='thanks'),
    path('profile', views.profile, name='profile'),
    path('terms', views.terms, name='terms'),
    path('aboutus', views.aboutus, name='aboutus'),
    path('map', views.map, name='map'),
    path('', views.top, name='top'),
    path('home', views.home, name='home'),
    path('send_test_mail', views.send_simple_message, name='send_test_mail'),
]

museum/models.py
from django.db import models

# Create your models here.
from django.conf import settings
from django.utils import timezone


class Store(models.Model):
    """店舗"""
    name = models.CharField('店名', max_length=255)

    class Meta:
        verbose_name = '店舗'
        verbose_name_plural = '店舗'

    def __str__(self):
        return self.name


class Staff(models.Model):
    """店舗スタッフ"""
    name = models.CharField('表示名', max_length=50)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name='ログインユーザー', on_delete=models.CASCADE
    )
    store = models.ForeignKey(Store, verbose_name='店舗', on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'store'], name='unique_staff'),
        ]
        verbose_name = 'スタッフ'
        verbose_name_plural = 'スタッフ'

    def __str__(self):
        return f'{self.store.name} - {self.name}'


class Schedule(models.Model):
    """予約スケジュール."""
    start = models.DateTimeField('開始時間')
    end = models.DateTimeField('終了時間')
    name = models.CharField('予約者名', max_length=255)
    email = models.CharField('メールアドレス', max_length=255, default='メールアドレス@')
    number = models.CharField('電話番号', max_length=255,blank=True, null=True, default='電話番号')
    staff = models.ForeignKey('Staff', verbose_name='スタッフ', on_delete=models.CASCADE,blank=True, null=True)

    class Meta:
        verbose_name = 'スケジュール'
        verbose_name_plural = 'スケジュール'

    def __str__(self):
        start = timezone.localtime(self.start).strftime('%Y/%m/%d %H:%M:%S')
        end = timezone.localtime(self.end).strftime('%Y/%m/%d %H:%M:%S')
        return f'{self.name} {start} ~ {end} {self.staff}'




class Post(models.Model):
    title = models.CharField(max_length=200,default='タイトル')
    price = models.CharField(max_length=200,blank=True, null=True)
    text = models.TextField(max_length=100000,blank=True, null=True,default='本文')
    created_date = models.DateTimeField('制作日',default=timezone.now,null=True)
    published_date = models.DateTimeField('発表日',blank=True, null=True)
    
    def publish(self):
        self.published_date = timezone.now()
        self.save()


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'メニュー'
        verbose_name_plural = 'メニュー'

class News(models.Model):
    GENRE_CHOICES = (
        (u'日記', u'日記'),
        (u'お得情報', u'お得情報'),
        (u'お知らせ', u'お知らせ'),
        (u'その他', u'その他'),
    )
    genre = models.CharField('ジャンル',max_length=200,blank=True, null=True, choices=GENRE_CHOICES)
    title = models.CharField('タイトル',max_length=200,blank=True, null=True)
    text = models.TextField('本文',blank=True, null=True)
    created_date = models.DateTimeField('制作日',default=timezone.now,null=True)
    published_date = models.DateTimeField('発表日',blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()
    
    class Meta:
        verbose_name = 'ニュース'
        verbose_name_plural = 'ニュース'
    
    def __str__(self):
        return self.title


class Profile(models.Model):
    title = models.CharField('名前',max_length=200,blank=True, null=True)
    text = models.TextField('自己紹介',blank=True, null=True)
    created_date = models.DateTimeField('制作日',default=timezone.now,null=True)
    published_date = models.DateTimeField('発表日',blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()
    
    class Meta:
        verbose_name = 'プロフィール'
        verbose_name_plural = 'プロフィール'

    def __str__(self):
        return self.title


class PictureForPost(models.Model):
    post = models.ForeignKey('museum.Post', on_delete=models.CASCADE, related_name='pictureforpost')
    avator = models.CharField('URL',max_length=200,blank=True, null=True)
    

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.avator
    
    class Meta:
        verbose_name = 'メニュー写真'
        verbose_name_plural = 'メニュー写真'


class PictureForNews(models.Model):
    news = models.ForeignKey('museum.News', on_delete=models.CASCADE, related_name='picturefornews')
    avator = models.CharField('URL',max_length=200,blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.avator

    class Meta:
        verbose_name = 'ニュース写真'
        verbose_name_plural = 'ニュース写真'

class PictureForProfile(models.Model):
    profile = models.ForeignKey('museum.Profile', on_delete=models.CASCADE, related_name='pictureforprofile')
    avator = models.CharField('URL',max_length=200,blank=True, null=True)
    

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.avator
    
    class Meta:
        verbose_name = 'ブログ写真'
        verbose_name_plural = 'ブログ写真'

museum/forms.py
from django import forms
from .models import  Comment

museum/views.py
import datetime
from django.conf import settings
from django.db.models import Q

from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.mail import send_mail, BadHeaderError

from django.shortcuts import render, get_object_or_404
from django.views import generic

from django.shortcuts import redirect
from django.utils import timezone
from django.template import Context, Template
from django.template.loader import render_to_string
from .models import Store, Staff, Schedule, Post, News, Profile, PictureForPost, PictureForNews

from django.core.mail import send_mail
from django.conf import settings

# Create your views here.

def home(request):
    return render(request, 'museum/home.html')


def send_simple_message(context, staff, schedule):
    storemail = "bacistyle2020@gmail.com"
    subject = 'Beauty salon bijouの予約が完了しました'
    email_from = settings.EMAIL_HOST_USER
    recipient_list = [schedule.email,storemail]

    print(recipient_list)
    message = f"{schedule.name}様<br /><br />"
    message += f"Beauty salon bijouの予約が完了しました。<br /><br />"
    message += "予約日時："+context["h"]+"〜 <br />"
    message += f"スタッフ:{staff}"
    message += "<br /><br />"
    message += f"ご予約の変更は<a href=\"mailto:{storemail}\">こちら</a>まで"
    message += "<br /><br />※このメールは返信不可です。"
    message += f"お客様の電話番号<a href=\"tel:{schedule.number}\">{schedule.number}</a>"
    print(subject, message, email_from, recipient_list, message)
    print("res")
    print(send_mail(subject, message, email_from, recipient_list, html_message=message))
    return HttpResponse('Mail successfully sent')

class StoreList(generic.ListView):
    model = Store
    ordering = 'name'


class StaffList(generic.ListView):
    model = Staff
    ordering = 'name'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['store'] = self.store
        return context

    def get_queryset(self):
        store = self.store = get_object_or_404(Store, pk=self.kwargs['pk'])
        queryset = super().get_queryset().filter(store=store)
        return queryset


class StaffCalendar(generic.TemplateView):
    template_name = 'museum/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        staff = get_object_or_404(Staff, pk=self.kwargs['pk'])
        today = datetime.date.today()

        # どの日を基準にカレンダーを表示するかの処理。
        # 年月日の指定があればそれを、なければ今日からの表示。
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        day = self.kwargs.get('day')
        if year and month and day:
            base_date = datetime.date(year=year, month=month, day=day)
        else:
            base_date = today

        # カレンダーは1週間分表示するので、基準日から1週間の日付を作成しておく
        days = [base_date + datetime.timedelta(days=day) for day in range(7)]
        start_day = days[0]
        end_day = days[-1]

        # 9時から18時まで1時間刻み、1週間分の、値がTrueなカレンダーを作る
        calendar = {}
        hours = ["10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00","18:30","19:00"]
        for hour in hours:
            row = {}
            for day in days:
                row[day] = True
            calendar[hour] = row

        # カレンダー表示する最初と最後の日時の間にある予約を取得する
        start_time = datetime.datetime.combine(start_day, datetime.time(hour=9, minute=0, second=0))
        end_time = datetime.datetime.combine(end_day, datetime.time(hour=19, minute=0, second=0))
        for schedule in Schedule.objects.filter(staff=staff).exclude(Q(start__gt=end_time) | Q(end__lt=start_time)):
            local_dt = timezone.localtime(schedule.start)
            booking_date = local_dt.date()
            booking_hour = local_dt.hour
            booking_minute = local_dt.minute
            booking_hour = str(booking_hour).zfill(2) + ":" + str(booking_minute).zfill(2)
            if booking_hour in calendar and booking_date in calendar[booking_hour]:
                calendar[booking_hour][booking_date] = False

        context['staff'] = staff
        context['calendar'] = calendar
        context['days'] = days
        context['start_day'] = start_day
        context['end_day'] = end_day
        context['before'] = days[0] - datetime.timedelta(days=7)
        context['next'] = days[-1] + datetime.timedelta(days=1)
        context['today'] = today

       
        return context

class Booking(generic.CreateView):
    model = Schedule
    fields = ('name','email',"number")
    template_name = 'museum/booking.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['staff'] = get_object_or_404(Staff, pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        staff = get_object_or_404(Staff, pk=self.kwargs['pk'])
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        day = self.kwargs.get('day')
        hour = int(self.kwargs.get('hour') / 100)
        minute = self.kwargs.get('hour') % 100
        #email = self.kwargs.get('email')
        start = datetime.datetime(year=year, month=month, day=day, hour=hour, minute=minute)
        end = datetime.datetime(year=year, month=month, day=day, hour=hour + 1, minute=minute)
        if Schedule.objects.filter(staff=staff, start=start).exists():
            messages.error(self.request, 'すみません、入れ違いで予約がありました。別の日時はどうですか。')
        else:
            schedule = form.save(commit=False)
            schedule.staff = staff
            schedule.start = start
            schedule.month = month
            schedule.day = day
            schedule.end = end
            schedule.save()
            context = {
            "m": str(month),
            "d": str(day),
            "h": str(start),
            }
            
            print(schedule.email)
            send_simple_message(context, staff, schedule)

            if minute == 0:
                start = datetime.datetime(year=year, month=month, day=day, hour=hour, minute=minute+30)
                end = datetime.datetime(year=year, month=month, day=day, hour=hour + 1, minute=minute)
                second = Schedule(staff=staff, start=start, end=end, email=schedule.email, name=schedule.name)
                second.save()
                start = datetime.datetime(year=year, month=month, day=day, hour=hour + 1 , minute=minute)
                end = datetime.datetime(year=year, month=month, day=day, hour=hour + 1, minute=minute + 30)
                third = Schedule(staff=staff, start=start, end=end, email=schedule.email, name=schedule.name)
                third.save()
                start = datetime.datetime(year=year, month=month, day=day, hour=hour + 1, minute=minute + 30)
                end = datetime.datetime(year=year, month=month, day=day, hour=hour + 2, minute=minute)
                fourth = Schedule(staff=staff, start=start, end=end, email=schedule.email, name=schedule.name)
                fourth.save()
                start = datetime.datetime(year=year, month=month, day=day, hour=hour -1, minute=minute+30)
                end = datetime.datetime(year=year, month=month, day=day, hour=hour, minute=minute)
                fifth = Schedule(staff=staff, start=start, end=end, email=schedule.email, name=schedule.name)
                fifth.save()
                start = datetime.datetime(year=year, month=month, day=day, hour=hour -1, minute=minute)
                end = datetime.datetime(year=year, month=month, day=day, hour=hour - 1, minute=minute+30)
                sixth = Schedule(staff=staff, start=start, end=end, email=schedule.email, name=schedule.name)
                sixth.save()
                start = datetime.datetime(year=year, month=month, day=day, hour=hour - 2, minute=minute+30)
                end = datetime.datetime(year=year, month=month, day=day, hour=hour - 1, minute=minute)
                seventh = Schedule(staff=staff, start=start, end=end, email=schedule.email, name=schedule.name)
                seventh.save()
            else:
                start = datetime.datetime(year=year, month=month, day=day, hour=hour+1, minute=0)
                end = datetime.datetime(year=year, month=month, day=day, hour=hour + 1, minute=30)
                second = Schedule(staff=staff, start=start, end=end, email=schedule.email, name=schedule.name)
                second.save()
                start = datetime.datetime(year=year, month=month, day=day, hour=hour + 1 , minute=30)
                end = datetime.datetime(year=year, month=month, day=day, hour=hour + 2, minute=0)
                third = Schedule(staff=staff, start=start, end=end, email=schedule.email, name=schedule.name)
                third.save()
                start = datetime.datetime(year=year, month=month, day=day, hour=hour + 2, minute=0)
                end = datetime.datetime(year=year, month=month, day=day, hour=hour + 2, minute=30)
                fourth = Schedule(staff=staff, start=start, end=end, email=schedule.email, name=schedule.name)
                fourth.save()
                start = datetime.datetime(year=year, month=month, day=day, hour=hour, minute=0)
                end = datetime.datetime(year=year, month=month, day=day, hour=hour, minute=30)
                fifth = Schedule(staff=staff, start=start, end=end, email=schedule.email, name=schedule.name)
                fifth.save()
                start = datetime.datetime(year=year, month=month, day=day, hour=hour -1, minute=30)
                end = datetime.datetime(year=year, month=month, day=day, hour=hour, minute=0)
                sixth = Schedule(staff=staff, start=start, end=end, email=schedule.email, name=schedule.name)
                sixth.save()
                start = datetime.datetime(year=year, month=month, day=day, hour=hour - 1, minute=0)

museum/templates/museum/aboutus.html
{% extends 'museum/base.html' %}

{% block content %}
    <div>
        <h4>当サイトについて</h4><br />
        <p>私が全米各地を周り、揃えたレコードを紹介していくとともにアメリカの民俗文化、歴史を解説するオンラインミュージアムです。</p>
        <p>次世代の方にアメリカの文化を伝えるために始めました。</p>
        <p>レコードのご寄贈やご寄付は下記メールアドレスにご連絡いただければと思います。</p><br />
        <p><a href="mailto:shono.mercy.music&#64;gmail.com" class="text-dark">shono.mercy.music[at]gmail.com</a></p>
    </div>
{% endblock %}

museum/templates/museum/add_comment_to_post.html
{% extends 'museum/base.html' %}

{% block content %}
    <h3>コメント</h3>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">送信</button>
    </form>
{% endblock %}

museum/templates/museum/artists.html
{% extends 'museum/base.html' %}

{% block content %}
    <h4>Shono's Record Collection</h4>
    <h4><strong>&nbsp;{{ genre.name }}</strong></h4>
    <div class="accordion" id="accordionExample">
        {% for artist in artists %}
            <div class="card">
                <div class="card-header" id="heading{{ artist.id }}">
                    <h3 class="mb-0">
                        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse{{ artist.id }}" aria-expanded="true" aria-controls="collapse{{ artist.id }}">
                            <span class="text-dark">{{ artist.name }}</span>
                        </button>
                    </h3>
                </div>
                <div id ="collapse{{ artist.id }}" class="collapse" aria-labelledby="heading{{ artist.id }}" data-parent="#accordionExample">
                    <div class="card-body">
                        {% for post in artist.post_set.all %}
                            <div class="pl-4 py-1"><a href="/posts/{{ post.id }}">{{ post.title }}</a></div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

museum/templates/museum/calendar.html
{% extends 'museum/base.html' %}

{% block content %}

    <h1>{{ staff.store.name }}店 {{ staff.name }}</h1>
    <p>{{ start_day }} - {{ end_day }}</p>
    <table class="table table-bordered text-center" style="table-layout: fixed;width: 100%" border="1">
        <tr>
            <td></td>
            {% for day in days %}
                
                {% if day.weekday == 5 %}
                    <th style="color: blue;">{{ day | date:"D" }}</th>
                {% elif day.weekday == 6 %}
                    <th style="color: red;">{{ day | date:"D" }}</th>
                {% else %}
                    <th>{{ day | date:"D" }}</th>
                {% endif %}
            {% endfor %}
            <td></td>
            
        </tr>
        <tr>
            <td><a href="{% url 'museum:calendar' staff.pk before.year before.month before.day %}">前週</a></td>
            {% for day in days %}
                
                {% if day.weekday == 5 %}
                    <th style="color: blue;">{{ day | date:"d" }}</th>
                {% elif day.weekday == 6 %}
                    <th style="color: red;">{{ day | date:"d" }}</th>
                {% else %}
                    <th>{{ day | date:"d" }}</th>
                {% endif %}
            {% endfor %}
            <td><a href="{% url 'museum:calendar' staff.pk next.year next.month next.day %}">次週</a></td>
            
        </tr>

        {% for hour, schedules in calendar.items %}
            <tr style="font-size:10px">
                <td>
                 <small>{{hour}}</small> 
                </td>
                {% for dt, book in schedules.items %}
                    <td>
                        {% if dt <= today %}
                            -
                        {% elif book %}
                            {% load myfilters %}
                            <a href="{% url 'museum:booking' staff.pk dt.year dt.month dt.day hour|removecolon %}">○</a>
                        {% else %}
                        <a>×</a>
                        {% endif %}
                    </td>

                {% endfor %}
                <td>
                    <!--{{ hour }}-->
                </td>
            </tr>
        {% endfor %}

    </table>
{% endblock %}

museum/templates/museum/column_show.html
{% extends 'museum/base.html' %}

{% block content %}
    <div>
        <h2>{{ column.title }}</h2>
        {% if column.html %}
            <p>{{ column.text| safe }}</p>
        {% else %}
            <p>{{ column.text|linebreaksbr|urlize }}</p>
        {% endif %}
        <p>{{ column.published_date }}</p>
    </div>
{% endblock %}

museum/templates/museum/columns.html
{% extends 'museum/base.html' %}

{% block content %}
    <h4>コラム</h4><br />
    {% for column in columns %}
        <div>
            <a href="/columns/{{ column.id }}">{{ column.title }}</a>
            <p class＝"text-muted"><small>{{ column.published_date }}</small></p>
        </div>
    {% endfor %}
{% endblock %}

museum/templates/museum/dbs.html
{% extends 'museum/base.html' %}

{% block content %}
    <h4>Detroit Blues Society<br />翻訳記事</h4><br />
    {% for dbs in dbss %}
        <div>
            <a href="/dbs/{{ dbs.id }}">{{ dbs.title }}</a>
            <p class＝"text-muted"><small>{{ news.published_date }}</small></p>
        </div>
    {% endfor %}
{% endblock %}

museum/templates/museum/dbs_show.html
{% extends 'museum/base.html' %}

{% block content %}
    <div>
        <h2>{{ dbs.title }}</h2>
        <p>{{ dbs.text|linebreaksbr|urlize }}</p>
        <p>{{ dbs.published_date }}</p>
    </div>
{% endblock %}

museum/templates/museum/home.html
{% extends 'museum/base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home page</title>
</head>
<body>

    <a href="/send_test_mail">Send test mail</a>
     

</body>
</html>
{% endblock %}

museum/templates/museum/map.html
{% extends 'museum/base.html' %}

{% block content %}
<html lang="ja">

{% load static %}
<img src="{% static 'map1.jpg' %}"　width="250" height="500">



</body>
</html>
{% endblock %}

museum/templates/museum/news.html
{% extends 'museum/base.html' %}



    {% block content %}
　　　{% for news in newss %}
        
        <div class="container marketing">
            <!-- Three columns of text below the carousel -->
            <div class="row">
              <div class="col-lg-4">
                <img src="https://drive.google.com/uc?export=view&id={{ news.picturefornews.first.avator }}&usp=sharing" alt="Generic placeholder image" width="140" height="140">
                <!-- <h2>Heading</h2> -->
                <h2><a href="/news/{{ news.id }}">{{ news.title }}</a></h2>
                <p><a>{{ news.text }}</a></p>
                <!-- <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p> -->

              </div><!-- /.col-lg-4 -->
            </div><!-- /.row -->
        </div>
        
    　{% endfor %}
  　{% endblock %}

museum/templates/museum/staff_list.html
{% extends 'museum/base.html' %}

{% block content %}

    <h1>{{ store.name }}店 スタッフ一覧</h1>
    <ul>
        {% for staff in staff_list %}
            <li><a href="{% url 'museum:calendar' staff.pk %}">{{ staff.name }}</a></li>
            
        {% empty %}
            <li>まだスタッフがいません。</li>
        {% endfor %}
    </ul>
{% endblock %}

museum/templates/museum/terms.html
{% extends 'museum/base.html' %}

{% block content %}
    <div>
        プライバシーポリシー<br />
        <br />
        個人情報の利用目的<br />
        <br />
        当サイトでは、お問い合わせや記事へのコメントの際、名前やメールアドレス等の個人情報を入力いただく場合がございます。<br />
        取得した個人情報は、お問い合わせに対する回答や必要な情報を電子メールなどをでご連絡する場合に利用させていただくものであり、これらの目的以外では利用いたしません。<br />
        <br />
        広告について<br />
        <br />
        当サイトでは、第三者配信の広告サービス（Googleアドセンス、A8.net）を利用しており、ユーザーの興味に応じた商品やサービスの広告を表示するため、クッキー（Cookie）を使用しております。<br />
        クッキーを使用することで当サイトはお客様のコンピュータを識別できるようになりますが、お客様個人を特定できるものではありません。<br />
        <br />
        Cookieを無効にする方法やGoogleアドセンスに関する詳細は「広告 – ポリシーと規約 – Google」をご確認ください。<br />
        <br />
        アクセス解析ツールについて<br />
        <br />
        当サイトでは、Googleによるアクセス解析ツール「Googleアナリティクス」を利用しています。このGoogleアナリティクスはトラフィックデータの収集のためにクッキー（Cookie）を使用しております。トラフィックデータは匿名で収集されており、個人を特定するものではありません。<br />
        <br />
        コメントについて<br />
        <br />
        当サイトへのコメントを残す際に、IP アドレスを収集しています。<br />
        これはサイトの標準機能としてサポートされている機能で、スパムや荒らしへの対応以外にこのIPアドレスを使用することはありません。<br />
        <br />
        免責事項<br />
        <br />
        当サイトからのリンクやバナーなどで移動したサイトで提供される情報、サービス等について一切の責任を負いません。<br />
        <br />
        また当サイトのコンテンツ・情報について、できる限り正確な情報を提供するように努めておりますが、正確性や安全性を保証するものではありません。情報が古くなっていることもございます。<br />
        <br />
        当サイトに掲載された内容によって生じた損害等の一切の責任を負いかねますのでご了承ください。<br />
        <br />
        著作権について<br />
        <br />
        当サイトで掲載している文章や画像などにつきましては、無断転載することを禁止します。<br />
        <br />
        当サイトは著作権や肖像権の侵害を目的としたものではありません。著作権や肖像権に関して問題がございましたら、お問い合わせフォームよりご連絡ください。迅速に対応いたします。<br />
        <br />
        リンクについて<br />
        <br />
        当サイトは基本的にリンクフリーです。リンクを行う場合の許可や連絡は不要です。<br />
        <br />
        ただし、インラインフレームの使用や画像の直リンクはご遠慮ください。<br />
    </div>
{% endblock %}

<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
     {% for post in posts %}
      <div class="carousel-item active">
        <svg class="bd-placeholder-img bd-placeholder-img-lg d-block w-100" width="800" height="400" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: First slide"><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#555" dy=".3em">{{ post.title }}</text></svg>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    {% endfor %}
  </div>